language: node_js
node_js:
- lts/*
services:
- postgresql
before_script:
- psql -c 'create database financetracker;' -U postgres
env:
  matrix:
  - DATABASE_URL=postgres://postgres:@localhost/financetracker
